// src/lib/optimization/index.ts

/**
 * LAC VIET HR - Performance Optimization Module
 * Comprehensive performance optimization utilities
 */

// Lazy Loading
export {
  type LazyLoadOptions,
  type ChunkConfig,
  type IntersectionOptions,
  type LazyDataOptions,
  type VirtualListConfig,
  type ProgressiveLoadConfig,
  type SkeletonConfig,
  createLazyComponent,
  lazyLoadOnVisible,
  ChunkDefinitions,
  registerModule,
  preloadModule,
  preloadModules,
  preloadByPriority,
  RouteModuleMap,
  preloadForRoute,
  setupPredictivePreloading,
  createLazyDataLoader,
  getVirtualListRange,
  getWindowedItems,
  loadProgressively,
  generateSkeletonConfig,
} from './lazy-loading';

// Image Optimization
export {
  type ImageConfig,
  type ResponsiveImageConfig,
  type ImageDimensions,
  type ImageFormat,
  type OptimizationOptions,
  ImageSizes,
  QualityPresets,
  ImageBreakpoints,
  generateColorPlaceholder,
  generateGradientPlaceholder,
  generateShimmerPlaceholder,
  generateSizesAttribute,
  ResponsiveSizes,
  buildImageUrl,
  generateSrcSet,
  DefaultSrcSetWidths,
  getInitials,
  stringToColor,
  generateAvatarPlaceholder,
  buildAvatarConfig,
  buildThumbnailConfig,
  buildCardImageConfig,
  buildBannerConfig,
  getBestSupportedFormat,
  supportsFormat,
  preloadImage,
  preloadImages,
  preloadCriticalImages,
  AspectRatios,
  calculateDimensions,
  getDimensionsForAspectRatio,
} from './image-optimization';

// Bundle Configuration
export {
  type BundleAnalysis,
  type ChunkInfo,
  type AssetInfo,
  type SizeLimit,
  SizeBudgets,
  ExternalPackages,
  TranspilePackages,
  ChunkGroups,
  generateSplitChunksConfig,
  generateNextConfig,
  TurbopackConfig,
  SideEffectFreePackages,
  SSRExternals,
  parseSizeToBytes,
  formatBytes,
  checkSizeLimit,
  createDynamicImport,
  PrefetchHints,
} from './bundle-config';

// Performance Metrics
export {
  type WebVitalsMetric,
  type PerformanceMetrics,
  type ResourceMetrics,
  type CustomTiming,
  type LongTask,
  type MemoryInfo,
  type FrameRateStats,
  type PerformanceReport,
  WebVitalsThresholds,
  onWebVitals,
  reportWebVital,
  getMetricRating,
  getNavigationMetrics,
  getResourceMetrics,
  getResourceStats,
  startTiming,
  endTiming,
  getTiming,
  clearTimings,
  measureAsync,
  measureSync,
  startLongTaskMonitoring,
  getLongTasks,
  clearLongTasks,
  getMemoryInfo,
  startFrameRateMonitoring,
  getFrameRateStats,
  collectWebVital,
  generatePerformanceReport,
  sendPerformanceReport,
  initPerformanceMonitoring,
} from './performance-metrics';

// Service Worker
export {
  type CacheConfig,
  type ServiceWorkerConfig,
  type CacheStrategy,
  type CachePlugin,
  type RegistrationResult,
  type NetworkStatus,
  type NetworkStatusCallback,
  type SyncRequest,
  type PushSubscriptionConfig,
  DefaultServiceWorkerConfig,
  CacheStrategies,
  PrecacheManifest,
  RuntimeCachingRoutes,
  registerServiceWorker,
  unregisterServiceWorkers,
  onServiceWorkerUpdate,
  skipWaitingAndReload,
  getCacheNames,
  clearCache,
  clearAllCaches,
  getCacheStorageUsage,
  getNetworkStatus,
  onNetworkStatusChange,
  queueForSync,
  getSyncQueue,
  removeFromSyncQueue,
  clearSyncQueue,
  isPushSupported,
  requestPushPermission,
  subscribeToPush,
  unsubscribeFromPush,
} from './service-worker';
