import { IsNumber, IsOptional, IsInt, Min } from 'class-validator';
import { ApiPropertyOptional } from '@nestjs/swagger';
import { Type } from 'class-transformer';

export class UpdateRoiDto {
  @ApiPropertyOptional({ example: 75000, description: 'Revenue generated by this activity' })
  @IsOptional()
  @Type(() => Number)
  @IsNumber()
  @Min(0)
  revenueGenerated?: number;

  @ApiPropertyOptional({ example: 5000, description: 'Number of units impacted' })
  @IsOptional()
  @Type(() => Number)
  @IsInt()
  @Min(0)
  unitsImpacted?: number;
}
