import { IndexConfig, SearchableEntity, SearchModule } from '../types';

export const customerIndexConfig: IndexConfig = {
  name: 'index_customer',
  primaryKey: 'id',
  searchableAttributes: [
    'name',
    'email',
    'phone',
    'company',
    'address',
    'city',
    'country',
    'taxId',
    'description',
  ],
  filterableAttributes: [
    'status',
    'type',
    'country',
    'city',
    'createdAt',
    'updatedAt',
  ],
  sortableAttributes: [
    'createdAt',
    'updatedAt',
    'name',
  ],
  displayedAttributes: [
    'id',
    'entity',
    'module',
    'name',
    'email',
    'phone',
    'company',
    'address',
    'city',
    'country',
    'status',
    'url',
  ],
  synonyms: {
    'khách hàng': ['customer', 'client', 'buyer'],
    'công ty': ['company', 'organization', 'firm'],
    'liên hệ': ['contact', 'phone', 'email'],
  },
  stopWords: [
    'và',
    'là',
    'cái',
    'được',
    'có',
    'của',
    'để',
    'từ',
    'với',
    'trong',
    'trên',
  ],
};
