import { IndexConfig } from '../types';

export const employeeIndexConfig: IndexConfig = {
  name: 'index_employee',
  primaryKey: 'id',
  searchableAttributes: [
    'name',
    'email',
    'phone',
    'department',
    'position',
    'bio',
    'skills',
    'tags',
  ],
  filterableAttributes: [
    'status',
    'department',
    'position',
    'type',
    'createdAt',
    'updatedAt',
    'joinDate',
  ],
  sortableAttributes: [
    'createdAt',
    'updatedAt',
    'name',
    'department',
  ],
  displayedAttributes: [
    'id',
    'entity',
    'module',
    'name',
    'email',
    'phone',
    'department',
    'position',
    'status',
    'url',
  ],
  synonyms: {
    'nhân viên': ['employee', 'staff', 'worker'],
    'bộ phận': ['department', 'division', 'team'],
    'chức vụ': ['position', 'role', 'title'],
    'kỹ năng': ['skills', 'competency', 'expertise'],
  },
  stopWords: [
    'và',
    'là',
    'cái',
    'được',
    'có',
    'của',
    'để',
    'từ',
    'với',
    'trong',
    'trên',
  ],
};
