import { IndexConfig } from '../types';

export const invoiceIndexConfig: IndexConfig = {
  name: 'index_invoice',
  primaryKey: 'id',
  searchableAttributes: [
    'invoiceNumber',
    'customerName',
    'customerEmail',
    'description',
    'reference',
    'tags',
    'notes',
  ],
  filterableAttributes: [
    'status',
    'paymentStatus',
    'amount',
    'tax',
    'total',
    'createdAt',
    'updatedAt',
    'dueDate',
  ],
  sortableAttributes: [
    'createdAt',
    'updatedAt',
    'invoiceNumber',
    'amount',
    'total',
  ],
  displayedAttributes: [
    'id',
    'entity',
    'module',
    'invoiceNumber',
    'customerName',
    'customerEmail',
    'status',
    'paymentStatus',
    'amount',
    'tax',
    'total',
    'createdAt',
    'url',
  ],
  synonyms: {
    'hóa đơn': ['invoice', 'bill', 'receipt'],
    'khách hàng': ['customer', 'buyer', 'client'],
    'trạng thái': ['status', 'state', 'condition'],
    'số tiền': ['amount', 'sum', 'total'],
    'thuế': ['tax', 'vat'],
  },
  stopWords: [
    'và',
    'là',
    'cái',
    'được',
    'có',
    'của',
    'để',
    'từ',
    'với',
    'trong',
    'trên',
  ],
};
