import { IndexConfig } from '../types';

export const orderIndexConfig: IndexConfig = {
  name: 'index_order',
  primaryKey: 'id',
  searchableAttributes: [
    'orderNumber',
    'customerName',
    'customerEmail',
    'description',
    'reference',
    'tags',
  ],
  filterableAttributes: [
    'status',
    'paymentStatus',
    'shippingStatus',
    'total',
    'subtotal',
    'createdAt',
    'updatedAt',
    'dueDate',
  ],
  sortableAttributes: [
    'createdAt',
    'updatedAt',
    'orderNumber',
    'total',
  ],
  displayedAttributes: [
    'id',
    'entity',
    'module',
    'orderNumber',
    'customerName',
    'customerEmail',
    'status',
    'paymentStatus',
    'shippingStatus',
    'total',
    'subtotal',
    'createdAt',
    'url',
  ],
  synonyms: {
    'đơn hàng': ['order', 'purchase', 'request'],
    'khách hàng': ['customer', 'buyer', 'client'],
    'trạng thái': ['status', 'state', 'condition'],
    'tổng': ['total', 'sum', 'amount'],
    'thanh toán': ['payment', 'paid', 'pay'],
  },
  stopWords: [
    'và',
    'là',
    'cái',
    'được',
    'có',
    'của',
    'để',
    'từ',
    'với',
    'trong',
    'trên',
  ],
};
