import { IndexConfig } from '../types';

export const productIndexConfig: IndexConfig = {
  name: 'index_product',
  primaryKey: 'id',
  searchableAttributes: [
    'name',
    'sku',
    'barcode',
    'description',
    'category',
    'tags',
    'manufacturer',
    'unit',
  ],
  filterableAttributes: [
    'status',
    'category',
    'price',
    'stock',
    'createdAt',
    'updatedAt',
    'type',
  ],
  sortableAttributes: [
    'createdAt',
    'updatedAt',
    'name',
    'price',
    'stock',
  ],
  displayedAttributes: [
    'id',
    'entity',
    'module',
    'name',
    'sku',
    'barcode',
    'description',
    'category',
    'price',
    'stock',
    'status',
    'url',
  ],
  synonyms: {
    'sản phẩm': ['product', 'item', 'goods'],
    'mã số': ['sku', 'code', 'id'],
    'loại': ['category', 'type', 'class'],
    'giá': ['price', 'cost', 'value'],
    'kho': ['stock', 'inventory', 'warehouse'],
  },
  stopWords: [
    'và',
    'là',
    'cái',
    'được',
    'có',
    'của',
    'để',
    'từ',
    'với',
    'trong',
    'trên',
  ],
};
