import { IndexConfig } from '../types';

export const taskIndexConfig: IndexConfig = {
  name: 'index_task',
  primaryKey: 'id',
  searchableAttributes: [
    'title',
    'description',
    'assignee',
    'project',
    'tags',
    'comments',
    'attachments',
  ],
  filterableAttributes: [
    'status',
    'priority',
    'project',
    'assignee',
    'createdAt',
    'updatedAt',
    'dueDate',
  ],
  sortableAttributes: [
    'createdAt',
    'updatedAt',
    'dueDate',
    'priority',
  ],
  displayedAttributes: [
    'id',
    'entity',
    'module',
    'title',
    'description',
    'assignee',
    'project',
    'status',
    'priority',
    'dueDate',
    'url',
  ],
  synonyms: {
    'nhiệm vụ': ['task', 'job', 'work'],
    'dự án': ['project', 'program'],
    'trạng thái': ['status', 'state', 'condition'],
    'ưu tiên': ['priority', 'importance', 'urgency'],
    'người giao': ['assignee', 'owner', 'responsible'],
  },
  stopWords: [
    'và',
    'là',
    'cái',
    'được',
    'có',
    'của',
    'để',
    'từ',
    'với',
    'trong',
    'trên',
  ],
};
