{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "vierp.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "vierp.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.global.domain }}
    secretName: {{ include "vierp.fullname" . }}-tls
  {{- end }}
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - host: {{ .Values.global.domain }}
    http:
      paths:
      {{- range $appKey, $appConfig := .Values.apps }}
      {{- if $appConfig.enabled }}
      - path: /{{ include "vierp.appName" $appKey }}
        pathType: Prefix
        backend:
          service:
            name: {{ include "vierp.appFullname" (dict "root" $ "appKey" $appKey) }}
            port:
              number: {{ $appConfig.port }}
      {{- end }}
      {{- end }}
{{- end }}
