import type { PronunciationEntry } from "@/types/pronunciation";

const a = (
  level: PronunciationEntry["level"],
  vi: PronunciationEntry["vi"],
  ipa: string,
  soundsLike: string,
  phonemes: string[],
  syllables: string[],
  stressIndex: number,
  ukIpa = ipa,
): PronunciationEntry => ({
  level,
  vi,
  us: { ipa, soundsLike, phonemes, syllables, stressIndex },
  uk: { ipa: ukIpa, soundsLike, phonemes, syllables, stressIndex },
});

export const pronunciationData: Record<string, PronunciationEntry> = {
  hello: a("A1", [{ partOfSpeech: "interjection", meaning: "xin chao" }], "/hehˈloʊ/", "heh-LOH", ["HH", "EH", "L", "OW"], ["hel", "lo"], 1, "/həˈləʊ/"),
  name: a("A1", [{ partOfSpeech: "noun", meaning: "ten" }], "/neɪm/", "NAYM", ["N", "EY", "M"], ["name"], 0),
  cat: a("A1", [{ partOfSpeech: "noun", meaning: "con meo" }], "/kæt/", "kat", ["K", "AE", "T"], ["cat"], 0),
  dog: a("A1", [{ partOfSpeech: "noun", meaning: "con cho" }], "/dɔːɡ/", "dawg", ["D", "AO", "G"], ["dog"], 0, "/dɒɡ/"),
  water: a("A1", [{ partOfSpeech: "noun", meaning: "nuoc" }], "/ˈwɑː.t̬ɚ/", "WAH-der", ["W", "AA", "T", "ER"], ["wa", "ter"], 0, "/ˈwɔː.tə/"),
  food: a("A1", [{ partOfSpeech: "noun", meaning: "thuc an" }], "/fuːd/", "food", ["F", "UW", "D"], ["food"], 0),
  house: a("A1", [{ partOfSpeech: "noun", meaning: "ngoi nha" }], "/haʊs/", "hows", ["HH", "AW", "S"], ["house"], 0),
  school: a("A1", [{ partOfSpeech: "noun", meaning: "truong hoc" }], "/skuːl/", "skool", ["S", "K", "UW", "L"], ["school"], 0),
  book: a("A1", [{ partOfSpeech: "noun", meaning: "quyen sach" }], "/bʊk/", "book", ["B", "UH", "K"], ["book"], 0),
  teacher: a("A1", [{ partOfSpeech: "noun", meaning: "giao vien" }], "/ˈtiː.tʃɚ/", "TEE-chur", ["T", "IY", "CH", "ER"], ["teach", "er"], 0, "/ˈtiː.tʃə/"),
  friend: a("A1", [{ partOfSpeech: "noun", meaning: "ban be" }], "/frend/", "frend", ["F", "R", "EH", "N", "D"], ["friend"], 0),
  mother: a("A1", [{ partOfSpeech: "noun", meaning: "me" }], "/ˈmʌð.ɚ/", "MUH-thur", ["M", "AH", "DH", "ER"], ["moth", "er"], 0, "/ˈmʌð.ə/"),
  father: a("A1", [{ partOfSpeech: "noun", meaning: "bo, cha" }], "/ˈfɑː.ðɚ/", "FAH-thur", ["F", "AA", "DH", "ER"], ["fa", "ther"], 0, "/ˈfɑː.ðə/"),
  good: a("A1", [{ partOfSpeech: "adjective", meaning: "tot" }], "/ɡʊd/", "good", ["G", "UH", "D"], ["good"], 0),
  bad: a("A1", [{ partOfSpeech: "adjective", meaning: "xau, te" }], "/bæd/", "bad", ["B", "AE", "D"], ["bad"], 0),
  english: a("A1", [{ partOfSpeech: "noun", meaning: "tieng Anh" }], "/ˈɪŋ.ɡlɪʃ/", "ING-glish", ["IH", "NG", "G", "L", "IH", "SH"], ["Eng", "lish"], 0),
  phone: a("A1", [{ partOfSpeech: "noun", meaning: "dien thoai" }], "/foʊn/", "fohn", ["F", "OW", "N"], ["phone"], 0, "/fəʊn/"),
  coffee: a("A1", [{ partOfSpeech: "noun", meaning: "ca phe" }], "/ˈkɑː.fi/", "KAH-fee", ["K", "AA", "F", "IY"], ["cof", "fee"], 0, "/ˈkɒf.i/"),
  family: a("A1", [{ partOfSpeech: "noun", meaning: "gia dinh" }], "/ˈfæm.əl.i/", "FAM-uh-lee", ["F", "AE", "M", "AH", "L", "IY"], ["fam", "i", "ly"], 0),
  music: a("A1", [{ partOfSpeech: "noun", meaning: "am nhac" }], "/ˈmjuː.zɪk/", "MYOO-zik", ["M", "Y", "UW", "Z", "IH", "K"], ["mu", "sic"], 0),
  listen: a("A1", [{ partOfSpeech: "verb", meaning: "lang nghe" }], "/ˈlɪs.ən/", "LIS-un", ["L", "IH", "S", "AH", "N"], ["lis", "ten"], 0),
  patient: a("A2", [{ partOfSpeech: "noun", meaning: "benh nhan" }, { partOfSpeech: "adjective", meaning: "kien nhan" }], "/ˈpeɪ.ʃənt/", "PAY-shuhnt", ["P", "EY", "SH", "AH", "N", "T"], ["pa", "tient"], 0),
  information: a("A2", [{ partOfSpeech: "noun", meaning: "thong tin" }], "/ˌɪn.fɚˈmeɪ.ʃən/", "in-fer-MAY-shuhn", ["IH", "N", "F", "ER", "M", "EY", "SH", "AH", "N"], ["in", "for", "ma", "tion"], 2, "/ˌɪn.fəˈmeɪ.ʃən/"),
  important: a("A2", [{ partOfSpeech: "adjective", meaning: "quan trong" }], "/ɪmˈpɔːr.tənt/", "im-POR-tuhnt", ["IH", "M", "P", "AO", "R", "T", "AH", "N", "T"], ["im", "por", "tant"], 1, "/ɪmˈpɔː.tənt/"),
  question: a("A2", [{ partOfSpeech: "noun", meaning: "cau hoi" }], "/ˈkwes.tʃən/", "KWES-chuhn", ["K", "W", "EH", "S", "CH", "AH", "N"], ["ques", "tion"], 0),
  answer: a("A2", [{ partOfSpeech: "noun", meaning: "cau tra loi" }, { partOfSpeech: "verb", meaning: "tra loi" }], "/ˈæn.sɚ/", "AN-sur", ["AE", "N", "S", "ER"], ["an", "swer"], 0, "/ˈɑːn.sə/"),
  travel: a("A2", [{ partOfSpeech: "verb", meaning: "di du lich" }], "/ˈtræv.əl/", "TRAV-ul", ["T", "R", "AE", "V", "AH", "L"], ["trav", "el"], 0),
  station: a("A2", [{ partOfSpeech: "noun", meaning: "nha ga, tram" }], "/ˈsteɪ.ʃən/", "STAY-shuhn", ["S", "T", "EY", "SH", "AH", "N"], ["sta", "tion"], 0),
  hospital: a("A2", [{ partOfSpeech: "noun", meaning: "benh vien" }], "/ˈhɑː.spɪ.t̬əl/", "HAH-spi-tul", ["HH", "AA", "S", "P", "IH", "T", "AH", "L"], ["hos", "pi", "tal"], 0, "/ˈhɒs.pɪ.təl/"),
  morning: a("A2", [{ partOfSpeech: "noun", meaning: "buoi sang" }], "/ˈmɔːr.nɪŋ/", "MOR-ning", ["M", "AO", "R", "N", "IH", "NG"], ["morn", "ing"], 0, "/ˈmɔː.nɪŋ/"),
  evening: a("A2", [{ partOfSpeech: "noun", meaning: "buoi toi" }], "/ˈiːv.nɪŋ/", "EEV-ning", ["IY", "V", "N", "IH", "NG"], ["eve", "ning"], 0),
  language: a("A2", [{ partOfSpeech: "noun", meaning: "ngon ngu" }], "/ˈlæŋ.ɡwɪdʒ/", "LANG-gwij", ["L", "AE", "NG", "G", "W", "IH", "JH"], ["lan", "guage"], 0),
  picture: a("A2", [{ partOfSpeech: "noun", meaning: "buc tranh, hinh anh" }], "/ˈpɪk.tʃɚ/", "PIK-chur", ["P", "IH", "K", "CH", "ER"], ["pic", "ture"], 0, "/ˈpɪk.tʃə/"),
  minute: a("A2", [{ partOfSpeech: "noun", meaning: "phut" }], "/ˈmɪn.ɪt/", "MIN-it", ["M", "IH", "N", "IH", "T"], ["min", "ute"], 0),
  problem: a("A2", [{ partOfSpeech: "noun", meaning: "van de" }], "/ˈprɑː.bləm/", "PRAH-blum", ["P", "R", "AA", "B", "L", "AH", "M"], ["prob", "lem"], 0, "/ˈprɒb.ləm/"),
  office: a("A2", [{ partOfSpeech: "noun", meaning: "van phong" }], "/ˈɑː.fɪs/", "AH-fis", ["AA", "F", "IH", "S"], ["of", "fice"], 0, "/ˈɒf.ɪs/"),
  pronunciation: a("A2", [{ partOfSpeech: "noun", meaning: "cach phat am" }], "/prəˌnʌn.siˈeɪ.ʃən/", "pruh-nun-see-AY-shuhn", ["P", "R", "AH", "N", "AH", "N", "S", "IY", "EY", "SH", "AH", "N"], ["pro", "nun", "ci", "a", "tion"], 3),
  computer: a("A2", [{ partOfSpeech: "noun", meaning: "may tinh" }], "/kəmˈpjuː.t̬ɚ/", "kum-PYOO-der", ["K", "AH", "M", "P", "Y", "UW", "T", "ER"], ["com", "pu", "ter"], 1, "/kəmˈpjuː.tə/"),
  internet: a("A2", [{ partOfSpeech: "noun", meaning: "mang internet" }], "/ˈɪn.tɚ.net/", "IN-ter-net", ["IH", "N", "T", "ER", "N", "EH", "T"], ["in", "ter", "net"], 0, "/ˈɪn.tə.net/"),
  doctor: a("A2", [{ partOfSpeech: "noun", meaning: "bac si" }], "/ˈdɑːk.tɚ/", "DAHK-tur", ["D", "AA", "K", "T", "ER"], ["doc", "tor"], 0, "/ˈdɒk.tə/"),
};

export const dictionaryWords = Object.keys(pronunciationData);
