#!/usr/bin/env npx tsx
/**
 * Formula Engine Test Runner
 * Run with: npx tsx src/tests/run-tests.ts
 */

import { runFormulaTests } from './formula-engine.runner';

console.log('Starting Formula Engine Tests...\n');

const results = runFormulaTests();

// Generate markdown report
const generateReport = () => {
  const now = new Date().toISOString();

  let report = `# Formula Engine Test Results

## Test Run: ${now}

### Summary
| Metric | Value |
|--------|-------|
| ✅ Passed | ${results.passed} |
| ❌ Failed | ${results.failed} |
| 📊 Total | ${results.total} |
| 📈 Pass Rate | ${results.passRate}% |

`;

  if (results.results.length > 0) {
    report += `### Failed Tests

| # | Test | Formula | Expected | Actual |
|---|------|---------|----------|--------|
`;
    results.results.forEach((r: { description: string; formula: string; expected: unknown; actual: unknown }, i: number) => {
      const expected = typeof r.expected === 'object' ? JSON.stringify(r.expected) : String(r.expected);
      const actual = typeof r.actual === 'object' ? JSON.stringify(r.actual) : String(r.actual);
      report += `| ${i + 1} | ${r.description} | \`${r.formula}\` | ${expected} | ${actual} |\n`;
    });
  } else {
    report += `### All Tests Passed! 🎉

No failed tests to report.
`;
  }

  report += `
---
Generated by Formula Engine Test Suite
`;

  return report;
};

// Write report to file
import * as fs from 'fs';
import * as path from 'path';

const reportPath = path.join(process.cwd(), 'FORMULA-TEST-RESULTS.md');
fs.writeFileSync(reportPath, generateReport());
console.log(`\n📝 Report saved to: ${reportPath}`);

// Exit with appropriate code
process.exit(results.failed > 0 ? 1 : 0);
