services:
  - type: web
    name: vierp-tpm-web
    runtime: node
    region: singapore
    plan: starter
    buildCommand: cd apps/web && npm install --include=dev && npm run build
    startCommand: cd apps/web && npm start
    autoDeploy: true
    envVars:
      - key: VITE_API_URL
        value: https://tpo-api.prismy.in
      - key: NODE_ENV
        value: production
    domains:
      - tpm.prismy.in
